name: Build Docker Image CI

on:
  push:
    tags: [ v* ]

jobs:
  build-envoy-auth-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Authenticate to gcloud
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: access_token
          workload_identity_provider: "projects/784289151693/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "cyberhaven-github-actions@cyberhaven-cd.iam.gserviceaccount.com"

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: us-docker.pkg.dev/cyberhaven-cd/iap-auth-service
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


